<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>WinExe</OutputType>

    <StartupObject>SharpQuake.idTech1</StartupObject>
    <ApplicationIcon>quake.ico</ApplicationIcon>

    <Platforms>AnyCPU</Platforms>

    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>14</LangVersion>

	<AssemblyTitle>SharpQuake</AssemblyTitle>
	<Description></Description>
	<Company></Company>
	<Product>SharpQuake</Product>
	<Copyright>Copyright © 2010 Yury Kiselev, Updates: Daniel Cornelius (Jan 2019) optimus-code (Jun 2019)</Copyright>

	<AssemblyVersion>1.5.0.0</AssemblyVersion>
	<FileVersion>1.5.0.0</FileVersion>
	<Version>1.5.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SharpQuake.Framework\SharpQuake.Framework.csproj" />
    <ProjectReference Include="..\SharpQuake.Game\SharpQuake.Game.csproj" />
    <ProjectReference Include="..\SharpQuake.Renderer.OpenGL\SharpQuake.Renderer.OpenGL.csproj" />
    <ProjectReference Include="..\SharpQuake.Renderer\SharpQuake.Renderer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Hardware.Info" Version="110.0.0.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.9" />
    <PackageReference Include="NVorbis" Version="0.10.5" />
    <PackageReference Include="OpenTK" Version="4.9.4" />
    <PackageReference Include="OpenTK.Audio.OpenAL" Version="4.9.4" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>

</Project>