using SharpQuake.Framework;
using SharpQuake.Sys.Programs;
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

namespace SharpQuake.Sys.Programs
{
    public class ProgramsCSharpEmitter(
        ProgramsState state )
    {
        private readonly ProgramsState _state = state;

        public string WriteToGameRoot( string fileName = "GeneratedQuakeProgs.cs" )
        {
            if ( String.IsNullOrWhiteSpace( fileName ) )
                throw new ArgumentException( "File name cannot be empty.", nameof( fileName ) );

            if ( _state.Functions == null || _state.Statements == null )
                throw new InvalidOperationException( "ProgramsState has not loaded progs.dat yet." );

            var root = AppContext.BaseDirectory;
            Directory.CreateDirectory( root );

            var path = Path.Combine( root, fileName );
            File.WriteAllText( path, EmitSource( ), new UTF8Encoding( false ) );

            return path;
        }

        public string EmitSource( )
        {
            var methodNames = BuildFunctionMethodNames( );
            var sb = new StringBuilder( 1024 * 1024 );

            sb.AppendLine( "// ------------------------------------------------------------------------------" );
            sb.AppendLine( "// <auto-generated>" );
            sb.AppendLine( "// Generated from QuakeC progs.dat bytecode." );
            sb.AppendLine( "// This is low-level VM-equivalent C#, not recovered original QuakeC source." );
            sb.AppendLine( "// </auto-generated>" );
            sb.AppendLine( "// ------------------------------------------------------------------------------" );
            sb.AppendLine( );
            sb.AppendLine( "using System;" );
            sb.AppendLine( );
            sb.AppendLine( "namespace SharpQuake.Sys.Programs.Generated" );
            sb.AppendLine( "{" );
            sb.AppendLine( "    internal sealed class GeneratedQuakeProgs" );
            sb.AppendLine( "    {" );
            sb.AppendLine( "        private readonly IGeneratedQuakeCRuntime Rt;" );
            sb.AppendLine( );
            sb.AppendLine( "        public GeneratedQuakeProgs( IGeneratedQuakeCRuntime runtime )" );
            sb.AppendLine( "        {" );
            sb.AppendLine( "            Rt = runtime ?? throw new ArgumentNullException( nameof( runtime ) );" );
            sb.AppendLine( "        }" );
            sb.AppendLine( );

            EmitExecuteSwitch( sb, methodNames );
            EmitCallFromGlobal( sb );
            EmitFunctions( sb, methodNames );

            sb.AppendLine( "    }" );
            sb.AppendLine( );
            EmitRuntimeInterface( sb );
            sb.AppendLine( "}" );

            return sb.ToString( );
        }

        private void EmitExecuteSwitch( StringBuilder sb, IReadOnlyDictionary<int, string> methodNames )
        {
            sb.AppendLine( "        public void Execute( int functionIndex )" );
            sb.AppendLine( "        {" );
            sb.AppendLine( "            switch ( functionIndex )" );
            sb.AppendLine( "            {" );

            foreach ( var pair in methodNames )
                sb.AppendLine( $"                case {pair.Key}: {pair.Value}( ); return;" );

            sb.AppendLine( "                default:" );
            sb.AppendLine( "                    if ( Rt.TryGetBuiltinFunction( functionIndex, out var builtinIndex ) )" );
            sb.AppendLine( "                    {" );
            sb.AppendLine( "                        Rt.ExecuteBuiltin( builtinIndex, 0 );" );
            sb.AppendLine( "                        return;" );
            sb.AppendLine( "                    }" );
            sb.AppendLine( "                    Rt.RunError( $\"Unknown generated QuakeC function index {functionIndex}.\" );" );
            sb.AppendLine( "                    return;" );
            sb.AppendLine( "            }" );
            sb.AppendLine( "        }" );
            sb.AppendLine( );
        }

        private static void EmitCallFromGlobal( StringBuilder sb )
        {
            sb.AppendLine( "        private void CallFromGlobal( int functionOffset, int argCount )" );
            sb.AppendLine( "        {" );
            sb.AppendLine( "            var functionIndex = Rt.GetFunction( functionOffset );" );
            sb.AppendLine( );
            sb.AppendLine( "            if ( functionIndex == 0 )" );
            sb.AppendLine( "            {" );
            sb.AppendLine( "                Rt.RunError( \"NULL function\" );" );
            sb.AppendLine( "                return;" );
            sb.AppendLine( "            }" );
            sb.AppendLine( );
            sb.AppendLine( "            if ( Rt.TryGetBuiltinFunction( functionIndex, out var builtinIndex ) )" );
            sb.AppendLine( "            {" );
            sb.AppendLine( "                Rt.ExecuteBuiltin( builtinIndex, argCount );" );
            sb.AppendLine( "                return;" );
            sb.AppendLine( "            }" );
            sb.AppendLine( );
            sb.AppendLine( "            Rt.SetArgCount( argCount );" );
            sb.AppendLine( "            Execute( functionIndex );" );
            sb.AppendLine( "        }" );
            sb.AppendLine( );
        }

        private void EmitFunctions( StringBuilder sb, IReadOnlyDictionary<int, string> methodNames )
        {
            foreach ( var pair in methodNames )
            {
                var functionIndex = pair.Key;
                var methodName = pair.Value;
                var function = _state.Functions[functionIndex];

                var start = function.first_statement;
                var end = FindFunctionEnd( functionIndex );

                var qcName = SafeComment( _state.GetString( function.s_name ) );
                var qcFile = SafeComment( _state.GetString( function.s_file ) );

                sb.AppendLine( $"        // QuakeC function #{functionIndex}: {qcName}" );
                sb.AppendLine( $"        // Source file: {qcFile}" );
                sb.AppendLine( $"        private void {methodName}( )" );
                sb.AppendLine( "        {" );
                sb.AppendLine( $"            Rt.EnterFunction( {functionIndex} );" );
                sb.AppendLine( $"            goto {Label( start )};" );
                sb.AppendLine( );

                for ( var s = start; s <= end; s++ )
                {
                    var st = _state.Statements[s];
                    var op = ( ProgramOperator ) st.op;

                    sb.AppendLine( $"        {Label( s )}:" );
                    sb.AppendLine( $"            // {s}: {op} a={st.a} b={st.b} c={st.c}" );

                    EmitStatement( sb, s, st, start, end );
                    sb.AppendLine( );
                }

                sb.AppendLine( "            Rt.LeaveFunction( );" );
                sb.AppendLine( "            return;" );
                sb.AppendLine( "        }" );
                sb.AppendLine( );
            }
        }

        private void EmitStatement( StringBuilder sb, int statementIndex, Statement st, int start, int end )
        {
            var op = ( ProgramOperator ) st.op;
            var a = st.a;
            var b = st.b;
            var c = st.c;

            switch ( op )
            {
                case ProgramOperator.OP_ADD_F:
                    Line( sb, $"Rt.SetFloat( {c}, Rt.GetFloat( {a} ) + Rt.GetFloat( {b} ) );" );
                    EmitGotoNext( sb, statementIndex, end );
                    break;

                case ProgramOperator.OP_ADD_V:
                    Line( sb, $"Rt.SetVector( {c}, Rt.GetFloat( {a} ) + Rt.GetFloat( {b} ), Rt.GetFloat( {a + 1} ) + Rt.GetFloat( {b + 1} ), Rt.GetFloat( {a + 2} ) + Rt.GetFloat( {b + 2} ) );" );
                    EmitGotoNext( sb, statementIndex, end );
                    break;

                case ProgramOperator.OP_SUB_F:
                    Line( sb, $"Rt.SetFloat( {c}, Rt.GetFloat( {a} ) - Rt.GetFloat( {b} ) );" );
                    EmitGotoNext( sb, statementIndex, end );
                    break;

                case ProgramOperator.OP_SUB_V:
                    Line( sb, $"Rt.SetVector( {c}, Rt.GetFloat( {a} ) - Rt.GetFloat( {b} ), Rt.GetFloat( {a + 1} ) - Rt.GetFloat( {b + 1} ), Rt.GetFloat( {a + 2} ) - Rt.GetFloat( {b + 2} ) );" );
                    EmitGotoNext( sb, statementIndex, end );
                    break;

                case ProgramOperator.OP_MUL_F:
                    Line( sb, $"Rt.SetFloat( {c}, Rt.GetFloat( {a} ) * Rt.GetFloat( {b} ) );" );
                    EmitGotoNext( sb, statementIndex, end );
                    break;

                case ProgramOperator.OP_MUL_V:
                    Line( sb, $"Rt.SetFloat( {c}, Rt.GetFloat( {a} ) * Rt.GetFloat( {b} ) + Rt.GetFloat( {a + 1} ) * Rt.GetFloat( {b + 1} ) + Rt.GetFloat( {a + 2} ) * Rt.GetFloat( {b + 2} ) );" );
                    EmitGotoNext( sb, statementIndex, end );
                    break;

                case ProgramOperator.OP_MUL_FV:
                    Line( sb, $"Rt.SetVector( {c}, Rt.GetFloat( {a} ) * Rt.GetFloat( {b} ), Rt.GetFloat( {a} ) * Rt.GetFloat( {b + 1} ), Rt.GetFloat( {a} ) * Rt.GetFloat( {b + 2} ) );" );
                    EmitGotoNext( sb, statementIndex, end );
                    break;

                case ProgramOperator.OP_MUL_VF:
                    Line( sb, $"Rt.SetVector( {c}, Rt.GetFloat( {b} ) * Rt.GetFloat( {a} ), Rt.GetFloat( {b} ) * Rt.GetFloat( {a + 1} ), Rt.GetFloat( {b} ) * Rt.GetFloat( {a + 2} ) );" );
                    EmitGotoNext( sb, statementIndex, end );
                    break;

                case ProgramOperator.OP_DIV_F:
                    Line( sb, $"Rt.SetFloat( {c}, Rt.GetFloat( {a} ) / Rt.GetFloat( {b} ) );" );
                    EmitGotoNext( sb, statementIndex, end );
                    break;

                case ProgramOperator.OP_BITAND:
                    Line( sb, $"Rt.SetFloat( {c}, (int)Rt.GetFloat( {a} ) & (int)Rt.GetFloat( {b} ) );" );
                    EmitGotoNext( sb, statementIndex, end );
                    break;

                case ProgramOperator.OP_BITOR:
                    Line( sb, $"Rt.SetFloat( {c}, (int)Rt.GetFloat( {a} ) | (int)Rt.GetFloat( {b} ) );" );
                    EmitGotoNext( sb, statementIndex, end );
                    break;

                case ProgramOperator.OP_GE:
                    EmitBoolFloat( sb, c, $"Rt.GetFloat( {a} ) >= Rt.GetFloat( {b} )" );
                    EmitGotoNext( sb, statementIndex, end );
                    break;

                case ProgramOperator.OP_LE:
                    EmitBoolFloat( sb, c, $"Rt.GetFloat( {a} ) <= Rt.GetFloat( {b} )" );
                    EmitGotoNext( sb, statementIndex, end );
                    break;

                case ProgramOperator.OP_GT:
                    EmitBoolFloat( sb, c, $"Rt.GetFloat( {a} ) > Rt.GetFloat( {b} )" );
                    EmitGotoNext( sb, statementIndex, end );
                    break;

                case ProgramOperator.OP_LT:
                    EmitBoolFloat( sb, c, $"Rt.GetFloat( {a} ) < Rt.GetFloat( {b} )" );
                    EmitGotoNext( sb, statementIndex, end );
                    break;

                case ProgramOperator.OP_AND:
                    EmitBoolFloat( sb, c, $"Rt.GetFloat( {a} ) != 0 && Rt.GetFloat( {b} ) != 0" );
                    EmitGotoNext( sb, statementIndex, end );
                    break;

                case ProgramOperator.OP_OR:
                    EmitBoolFloat( sb, c, $"Rt.GetFloat( {a} ) != 0 || Rt.GetFloat( {b} ) != 0" );
                    EmitGotoNext( sb, statementIndex, end );
                    break;

                case ProgramOperator.OP_NOT_F:
                    EmitBoolFloat( sb, c, $"Rt.GetFloat( {a} ) == 0" );
                    EmitGotoNext( sb, statementIndex, end );
                    break;

                case ProgramOperator.OP_NOT_V:
                    EmitBoolFloat( sb, c, $"Rt.GetFloat( {a} ) == 0 && Rt.GetFloat( {a + 1} ) == 0 && Rt.GetFloat( {a + 2} ) == 0" );
                    EmitGotoNext( sb, statementIndex, end );
                    break;

                case ProgramOperator.OP_NOT_S:
                    EmitBoolFloat( sb, c, $"String.IsNullOrEmpty( Rt.GetStringValue( {a} ) )" );
                    EmitGotoNext( sb, statementIndex, end );
                    break;

                case ProgramOperator.OP_NOT_FNC:
                    EmitBoolFloat( sb, c, $"Rt.GetFunction( {a} ) == 0" );
                    EmitGotoNext( sb, statementIndex, end );
                    break;

                case ProgramOperator.OP_NOT_ENT:
                    EmitBoolFloat( sb, c, $"Rt.IsWorldEntity( {a} )" );
                    EmitGotoNext( sb, statementIndex, end );
                    break;

                case ProgramOperator.OP_EQ_F:
                    EmitBoolFloat( sb, c, $"Rt.GetFloat( {a} ) == Rt.GetFloat( {b} )" );
                    EmitGotoNext( sb, statementIndex, end );
                    break;

                case ProgramOperator.OP_EQ_V:
                    EmitBoolFloat( sb, c, $"Rt.GetFloat( {a} ) == Rt.GetFloat( {b} ) && Rt.GetFloat( {a + 1} ) == Rt.GetFloat( {b + 1} ) && Rt.GetFloat( {a + 2} ) == Rt.GetFloat( {b + 2} )" );
                    EmitGotoNext( sb, statementIndex, end );
                    break;

                case ProgramOperator.OP_EQ_S:
                    EmitBoolFloat( sb, c, $"Rt.GetStringValue( {a} ) == Rt.GetStringValue( {b} )" );
                    EmitGotoNext( sb, statementIndex, end );
                    break;

                case ProgramOperator.OP_EQ_E:
                case ProgramOperator.OP_EQ_FNC:
                    EmitBoolFloat( sb, c, $"Rt.GetInt( {a} ) == Rt.GetInt( {b} )" );
                    EmitGotoNext( sb, statementIndex, end );
                    break;

                case ProgramOperator.OP_NE_F:
                    EmitBoolFloat( sb, c, $"Rt.GetFloat( {a} ) != Rt.GetFloat( {b} )" );
                    EmitGotoNext( sb, statementIndex, end );
                    break;

                case ProgramOperator.OP_NE_V:
                    EmitBoolFloat( sb, c, $"Rt.GetFloat( {a} ) != Rt.GetFloat( {b} ) || Rt.GetFloat( {a + 1} ) != Rt.GetFloat( {b + 1} ) || Rt.GetFloat( {a + 2} ) != Rt.GetFloat( {b + 2} )" );
                    EmitGotoNext( sb, statementIndex, end );
                    break;

                case ProgramOperator.OP_NE_S:
                    EmitBoolFloat( sb, c, $"Rt.GetStringValue( {a} ) != Rt.GetStringValue( {b} )" );
                    EmitGotoNext( sb, statementIndex, end );
                    break;

                case ProgramOperator.OP_NE_E:
                case ProgramOperator.OP_NE_FNC:
                    EmitBoolFloat( sb, c, $"Rt.GetInt( {a} ) != Rt.GetInt( {b} )" );
                    EmitGotoNext( sb, statementIndex, end );
                    break;

                case ProgramOperator.OP_STORE_F:
                case ProgramOperator.OP_STORE_ENT:
                case ProgramOperator.OP_STORE_FLD:
                case ProgramOperator.OP_STORE_S:
                case ProgramOperator.OP_STORE_FNC:
                    Line( sb, $"Rt.SetInt( {b}, Rt.GetInt( {a} ) );" );
                    EmitGotoNext( sb, statementIndex, end );
                    break;

                case ProgramOperator.OP_STORE_V:
                    Line( sb, $"Rt.CopyVector( {a}, {b} );" );
                    EmitGotoNext( sb, statementIndex, end );
                    break;

                case ProgramOperator.OP_STOREP_F:
                case ProgramOperator.OP_STOREP_ENT:
                case ProgramOperator.OP_STOREP_FLD:
                case ProgramOperator.OP_STOREP_S:
                case ProgramOperator.OP_STOREP_FNC:
                    Line( sb, $"Rt.StorePointerInt( {b}, {a} );" );
                    EmitGotoNext( sb, statementIndex, end );
                    break;

                case ProgramOperator.OP_STOREP_V:
                    Line( sb, $"Rt.StorePointerVector( {b}, {a} );" );
                    EmitGotoNext( sb, statementIndex, end );
                    break;

                case ProgramOperator.OP_ADDRESS:
                    Line( sb, $"Rt.MakeAddress( {a}, {b}, {c} );" );
                    EmitGotoNext( sb, statementIndex, end );
                    break;

                case ProgramOperator.OP_LOAD_F:
                case ProgramOperator.OP_LOAD_FLD:
                case ProgramOperator.OP_LOAD_ENT:
                case ProgramOperator.OP_LOAD_S:
                case ProgramOperator.OP_LOAD_FNC:
                    Line( sb, $"Rt.LoadInt( {a}, {b}, {c} );" );
                    EmitGotoNext( sb, statementIndex, end );
                    break;

                case ProgramOperator.OP_LOAD_V:
                    Line( sb, $"Rt.LoadVector( {a}, {b}, {c} );" );
                    EmitGotoNext( sb, statementIndex, end );
                    break;

                case ProgramOperator.OP_IF:
                    EmitConditionalJump( sb, $"Rt.GetInt( {a} ) != 0", statementIndex + b, statementIndex + 1, start, end );
                    break;

                case ProgramOperator.OP_IFNOT:
                    EmitConditionalJump( sb, $"Rt.GetInt( {a} ) == 0", statementIndex + b, statementIndex + 1, start, end );
                    break;

                case ProgramOperator.OP_GOTO:
                    EmitJump( sb, statementIndex + a, start, end );
                    break;

                case ProgramOperator.OP_CALL0:
                case ProgramOperator.OP_CALL1:
                case ProgramOperator.OP_CALL2:
                case ProgramOperator.OP_CALL3:
                case ProgramOperator.OP_CALL4:
                case ProgramOperator.OP_CALL5:
                case ProgramOperator.OP_CALL6:
                case ProgramOperator.OP_CALL7:
                case ProgramOperator.OP_CALL8:
                    var argCount = st.op - ( int ) ProgramOperator.OP_CALL0;
                    Line( sb, $"CallFromGlobal( {a}, {argCount} );" );
                    EmitGotoNext( sb, statementIndex, end );
                    break;

                case ProgramOperator.OP_DONE:
                case ProgramOperator.OP_RETURN:
                    Line( sb, $"Rt.ReturnValue( {a} );" );
                    Line( sb, "Rt.LeaveFunction( );" );
                    Line( sb, "return;" );
                    break;

                case ProgramOperator.OP_STATE:
                    Line( sb, $"Rt.State( {a}, {b} );" );
                    EmitGotoNext( sb, statementIndex, end );
                    break;

                default:
                    Line( sb, $"Rt.RunError( \"Bad opcode {st.op} at statement {statementIndex}.\" );" );
                    Line( sb, "return;" );
                    break;
            }
        }

        private void EmitGotoNext( StringBuilder sb, int statementIndex, int end )
        {
            var next = statementIndex + 1;

            if ( next <= end )
                Line( sb, $"goto {Label( next )};" );
            else
                Line( sb, "return;" );
        }

        private static void EmitBoolFloat( StringBuilder sb, int dest, string expression )
        {
            Line( sb, $"Rt.SetFloat( {dest}, ( {expression} ) ? 1f : 0f );" );
        }

        private static void EmitConditionalJump( StringBuilder sb, string expression, int trueTarget, int falseTarget, int start, int end )
        {
            Line( sb, $"if ( {expression} )" );
            Line( sb, "{" );

            if ( trueTarget >= start && trueTarget <= end )
                Line( sb, $"    goto {Label( trueTarget )};" );
            else
                Line( sb, $"    Rt.RunError( \"Invalid generated jump target {trueTarget}.\" ); return;" );

            Line( sb, "}" );

            if ( falseTarget >= start && falseTarget <= end )
                Line( sb, $"goto {Label( falseTarget )};" );
            else
                Line( sb, $"Rt.RunError( \"Invalid generated jump target {falseTarget}.\" ); return;" );
        }

        private static void EmitJump( StringBuilder sb, int target, int start, int end )
        {
            if ( target >= start && target <= end )
                Line( sb, $"goto {Label( target )};" );
            else
                Line( sb, $"Rt.RunError( \"Invalid generated jump target {target}.\" ); return;" );
        }

        private int FindFunctionEnd( int functionIndex )
        {
            var function = _state.Functions[functionIndex];
            var start = function.first_statement;
            var end = _state.Statements.Length - 1;

            for ( var i = 0; i < _state.Functions.Length; i++ )
            {
                if ( i == functionIndex )
                    continue;

                var otherStart = _state.Functions[i].first_statement;

                if ( otherStart > start && otherStart - 1 < end )
                    end = otherStart - 1;
            }

            return end;
        }

        private Dictionary<int, string> BuildFunctionMethodNames( )
        {
            var result = new Dictionary<int, string>( );
            var used = new HashSet<string>( StringComparer.Ordinal );

            for ( var i = 0; i < _state.Functions.Length; i++ )
            {
                var function = _state.Functions[i];

                if ( function == null || function.first_statement <= 0 )
                    continue;

                var rawName = _state.GetString( function.s_name );
                var cleanName = ToIdentifier( rawName );

                var methodName = $"Fn_{i:D4}_{cleanName}";
                var baseName = methodName;
                var suffix = 2;

                while ( used.Contains( methodName ) )
                    methodName = $"{baseName}_{suffix++}";

                used.Add( methodName );
                result[i] = methodName;
            }

            return result;
        }

        private static string ToIdentifier( string value )
        {
            if ( String.IsNullOrWhiteSpace( value ) )
                return "anonymous";

            var sb = new StringBuilder( value.Length );

            for ( var i = 0; i < value.Length; i++ )
            {
                var ch = value[i];

                if ( Char.IsLetterOrDigit( ch ) || ch == '_' )
                    sb.Append( ch );
                else
                    sb.Append( '_' );
            }

            if ( sb.Length == 0 )
                return "anonymous";

            if ( !Char.IsLetter( sb[0] ) && sb[0] != '_' )
                sb.Insert( 0, '_' );

            return sb.ToString( );
        }

        private static string Label( int statementIndex )
        {
            return $"st_{statementIndex:D6}";
        }

        private static string SafeComment( string value )
        {
            if ( String.IsNullOrEmpty( value ) )
                return String.Empty;

            return value
                .Replace( "\r", " " )
                .Replace( "\n", " " )
                .Replace( "*/", "* /" );
        }

        private static void Line( StringBuilder sb, string text )
        {
            sb.Append( "            " );
            sb.AppendLine( text );
        }

        private static void EmitRuntimeInterface( StringBuilder sb )
        {
            sb.AppendLine( "    internal interface IGeneratedQuakeCRuntime" );
            sb.AppendLine( "    {" );
            sb.AppendLine( "        void EnterFunction( int functionIndex );" );
            sb.AppendLine( "        void LeaveFunction( );" );
            sb.AppendLine( "        void SetArgCount( int argCount );" );
            sb.AppendLine( );
            sb.AppendLine( "        int GetInt( int offset );" );
            sb.AppendLine( "        void SetInt( int offset, int value );" );
            sb.AppendLine( );
            sb.AppendLine( "        float GetFloat( int offset );" );
            sb.AppendLine( "        void SetFloat( int offset, float value );" );
            sb.AppendLine( );
            sb.AppendLine( "        int GetFunction( int offset );" );
            sb.AppendLine( "        string GetStringValue( int offset );" );
            sb.AppendLine( "        bool IsWorldEntity( int offset );" );
            sb.AppendLine( );
            sb.AppendLine( "        void SetVector( int offset, float x, float y, float z );" );
            sb.AppendLine( "        void CopyVector( int sourceOffset, int destinationOffset );" );
            sb.AppendLine( );
            sb.AppendLine( "        void StorePointerInt( int addressOffset, int sourceOffset );" );
            sb.AppendLine( "        void StorePointerVector( int addressOffset, int sourceOffset );" );
            sb.AppendLine( );
            sb.AppendLine( "        void MakeAddress( int edictOffset, int fieldOffset, int destinationOffset );" );
            sb.AppendLine( "        void LoadInt( int edictOffset, int fieldOffset, int destinationOffset );" );
            sb.AppendLine( "        void LoadVector( int edictOffset, int fieldOffset, int destinationOffset );" );
            sb.AppendLine( );
            sb.AppendLine( "        bool TryGetBuiltinFunction( int functionIndex, out int builtinIndex );" );
            sb.AppendLine( "        void ExecuteBuiltin( int builtinIndex, int argCount );" );
            sb.AppendLine( );
            sb.AppendLine( "        void ReturnValue( int sourceOffset );" );
            sb.AppendLine( "        void State( int frameOffset, int thinkOffset );" );
            sb.AppendLine( "        void RunError( string message );" );
            sb.AppendLine( "    }" );
        }
    }
}