<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Resources\GLSL\DefaultSurface.frag" />
    <None Remove="Resources\GLSL\DefaultSurface.vert" />
    <None Remove="Resources\GLSL\PostFX.frag" />
    <None Remove="Resources\GLSL\PostFX.vert" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\GLSL\PostFX.vert" />
    <EmbeddedResource Include="Resources\GLSL\PostFX.frag" />
    <EmbeddedResource Include="Resources\GLSL\DefaultSurface.frag" />
    <EmbeddedResource Include="Resources\GLSL\DefaultSurface.vert" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SharpQuake.Framework\SharpQuake.Framework.csproj" />
    <ProjectReference Include="..\SharpQuake.Renderer\SharpQuake.Renderer.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="OpenTK" Version="4.9.4" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="System.Drawing.Common" Version="11.0.0-preview.5.26302.115" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>
</Project>